#PARA PRODUCCION

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        prepareThreshold: 0

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        prepare_all_queries: false

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}

apis:
  netpe:
    token: ${APIS_NETPE_TOKEN:}
    base-url: ${APIS_NETPE_BASE_URL:https://api.decolecta.com}

logging:
  level:
    org.hibernate.SQL: INFO
    com.hotel.sistemahotel: INFO